//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISKON_VyasaPuja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VyasaPuja
    {
        public int Vyasapujaid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string AlphabetFirstLetter { get; set; }
        public string Year { get; set; }
    }
}
